export const LOAD_TODO_REQUEST = "LOAD_TODO_REQUEST";
export const LOAD_TODO_SUCCESS = "LOAD_TODO_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const LOAD_TODO_ERROR = "LOAD_TODO_ERROR";
